### PR TITLE
Checks to make sure a valid formatter was specified fixes #11

### LINKED ISSUE #11: nsp implodes if you specify an invalid reporter name
For fun, I set my output reporter/formatter as "summaryz". This happens:

``` sh
✗ grunt nsp

Running "nsp" task
fxa-content-server.CRITICAL: uncaughtException TypeError: undefined is not a function
    at /Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp/tasks/nsp.js:44:20
    at /Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp/node_modules/nsp/lib/check.js:214:7
    at /Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp/node_modules/nsp/node_modules/wreck/lib/index.js:472:20
    at finish (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp/node_modules/nsp/node_modules/wreck/lib/index.js:326:16)
    at wrapped (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp/node_modules/nsp/node_modules/hoek/lib/index.js:866:20)
    at onReaderFinish (/Users/pdehaan/dev/fxa-content-server_pd/fxa-content-server/node_modules/grunt-nsp/node_modules/nsp/node_modules/wreck/lib/index.js:363:16)
    at g (events.js:199:16)
    at emit (events.js:129:20)
    at finishMaybe (_stream_writable.js:484:14)
    at endWritable (_stream_writable.js:493:3)
    at Writable.end (_stream_writable.js:459:5)
    at IncomingMessage.onend (_stream_readable.js:505:10)
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
Fatal error: undefined is not a function
```

We may want to add a quick check to make sure that the user specified a valid reporter.

### PR DESCRIPTION
**Pull request by evilpacket**

### CODE REVIEW

File: tasks/nsp.js [hunk 1]
```diff
@@ -36,8 +41,13 @@ module.exports = function (grunt) {
 
     if (grunt.option('output')) {
       formatter = Nsp.formatters[grunt.option('output')];
-    }
 
+      if (formatters.indexOf(config.output) !== -1) {
```
Comment (pdehaan) [inline tasks/nsp.js]: Not sure if ESLint complains (if we're running it against this repo), but it almost looks like `formatters` is out of scope here since it was declared within a `if(){...}` block above (but not really due to variable hoisting).

Comment (pdehaan) [inline tasks/nsp.js]: also, should this be `config.output` here, or `grunt.option('output')`?

File: tasks/nsp.js [hunk 2]
```diff
@@ -21,7 +21,12 @@ module.exports = function (grunt) {
     }
 
     if (config.output) {
-      formatter = Nsp.formatters[config.output];
+      var formatters = Object.keys(Nsp.formatters);
+      if (formatters.indexOf(config.output) !== -1) {
+        formatter = Nsp.formatters[config.output];
+      } else {
+        grunt.log.write('Invalid formatter specified in config. Must be one of ' + Object.keys(Nsp.formatters).join(',') + '\n');
```
Comment (pdehaan) [inline tasks/nsp.js:28]: You can replace `Object.keys(Nsp.formatters)` here with `formatters` (from line 24).

File: tasks/nsp.js [hunk 3]
```diff
@@ -36,8 +41,13 @@ module.exports = function (grunt) {
 
     if (grunt.option('output')) {
       formatter = Nsp.formatters[grunt.option('output')];
-    }
 
+      if (formatters.indexOf(config.output) !== -1) {
+        formatter = Nsp.formatters[grunt.option('output')];
+      } else {
+        grunt.log.write('Invalid formatter specified in options. Must be one of ' + Object.keys(Nsp.formatters).join(',') + '\n');
```
Comment (pdehaan) [inline tasks/nsp.js:47]: You can replace `Object.keys(Nsp.formatters)` here with `formatters` (from line 24).

File: tasks/nsp.js (hunk 1 above)
Comment (pdehaan) [inline tasks/nsp.js]: Do we still need line 43 above, or is it replaced by line 46 below?

File: tasks/nsp.js [hunk 4]
```diff
@@ -21,7 +21,12 @@ module.exports = function (grunt) {
     }
 
     if (config.output) {
-      formatter = Nsp.formatters[config.output];
+      var formatters = Object.keys(Nsp.formatters);
+      if (formatters.indexOf(config.output) !== -1) {
```
Comment (nlf) [inline tasks/nsp.js]: why not just `if (Nsp.formatters.hasOwnProperty(config.output))` ?

**Comment by nlf** [comment]
+1
